services:
  price-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    command:  watchfiles 'python services/processors/price_fetcher/main.py'
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/worker_ready"]
      interval: 5s
      timeout: 2s
      retries: 20
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
  
  signal-evaluator:
    build:
      context: .
      dockerfile: Dockerfile
    command:  watchfiles 'python services/processors/signal_evaluator/main.py'
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/worker_ready"]
      interval: 5s
      timeout: 2s
      retries: 20
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app

networks:
  event-net:
    external: true