version: "3.9"

services:

  telegram-producer:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && watchfiles 'python services/producers/telegram/main.py'"
    restart: always

    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

  scraper-producer:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && watchfiles 'python services/producers/scraper/main.py'"
    restart: always

    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

  http-api-producer:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && watchfiles 'python services/producers/http_api/main.py'"
    restart: always

    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

networks:
  event-net:
    external: true