services:
  engine:
    build: 
      context: .
      dockerfile: Dockerfile
    command:  sh -c "sleep 10 && watchfiles 'python services/engine/main.py'"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

  html-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command:  sh -c "sleep 10 && watchfiles 'python services/workers/html_cleaner/main.py'"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

  ai-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command:  sh -c "sleep 10 && watchfiles 'python services/workers/ai_worker/main.py'"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

  serializer:
    build: 
      context: .
      dockerfile: Dockerfile
    command:  sh -c "sleep 10 && watchfiles 'python services/workers/serializer/main.py'"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

  final-store:
    build: 
      context: .
      dockerfile: Dockerfile
    command:  sh -c "sleep 10 && watchfiles 'python services/workers/final_store/main.py'"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - event-net
    volumes:
      - .:/app

networks:
  event-net:
    external: true