"""add tracked_coins table with seed data from coins.json

Revision ID: a1b2c3d4e5f6
Revises: f4a5b6c7d8e9
Create Date: 2026-05-31 00:00:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "f4a5b6c7d8e9"
branch_labels = None
depends_on = None

# ── All 312 coins seeded from coins.json ──────────────────────────────────────
_COINS = [
    ("btc", "Bitcoin", "بیت‌کوین"),
    ("eth", "Ethereum", "اتریوم"),
    ("usdt", "Tether", "تتر"),
    ("shib", "Shiba Inu", "شیبا"),
    ("bch", "Bitcoin Cash", "بیت‌کوین‌کش"),
    ("ltc", "Litecoin", "لایت‌کوین"),
    ("etc", "Ethereum Classic", "اتریوم کلاسیک"),
    ("doge", "Dogecoin", "دوج‌کوین"),
    ("ada", "Cardano", "کاردانو"),
    ("bnb", "BNB", "بایننس‌کوین"),
    ("xrp", "XRP", "ریپل"),
    ("trx", "TRON", "ترون"),
    ("uni", "Uniswap", "یونی‌سواپ"),
    ("link", "Chainlink", "چین‌لینک"),
    ("dai", "Dai", "دای"),
    ("dot", "Polkadot", "پولکادات"),
    ("aave", "Aave", "آوه"),
    ("pmn", "peyman", "پیمان"),
    ("pol", "Polygon", "پالیگان"),
    ("axs", "Axie Infinity", "اکسی‌اینفینیتی"),
    ("mana", "Decentraland", "دیسنترالند"),
    ("sand", "The Sandbox", "سندباکس"),
    ("avax", "Avalanche", "آوالانچ"),
    ("usdc", "USDC", "یو‌اس‌‌دی‌کوین"),
    ("gmt", "GMT", "استپن"),
    ("mkr", "Maker", "میکر"),
    ("sol", "Solana", "سولانا"),
    ("atom", "Cosmos", "اتم"),
    ("grt", "The Graph", "گراف"),
    ("bat", "Basic Attention Token", "بیسیک اتنشن توکن"),
    ("near", "NEAR Protocol", "نیر پروتکل"),
    ("ape", "ApeCoin", "ایپ‌کوین"),
    ("qnt", "Quant", "کوانت"),
    ("chz", "Chiliz", "چیلیز"),
    ("xmr", "Monero", "مونرو"),
    ("egala", "Gala", "گالا"),
    ("busd", "BUSD", "بایننس یواس‌دی"),
    ("algo", "Algorand", "الگورند"),
    ("hbar", "Hedera", "هدرا"),
    ("1inch", "1inch Network", "وان اینچ نتورک"),
    ("yfi", "yearn finance", "یرن فایننس"),
    ("flow", "Flow", "فلو"),
    ("snx", "Synthetix", "سینتتیکس"),
    ("enj", "Enjin Coin", "انجین کوین"),
    ("crv", "Curve DAO Token", "کرو دائو توکن"),
    ("fil", "Filecoin", "فایل کوین"),
    ("wbtc", "Wrapped Bitcoin", "رپد بیت‌کوین"),
    ("ldo", "Lido DAO", "لیدو دائو"),
    ("dydx", "dYdX", "دی‌وای دی‌ایکس"),
    ("flr", "Flare", "فلر"),
    ("apt", "Aptos", "اپتاس"),
    ("mask", "Mask Network", "مسک نتورک"),
    ("comp", "Compound", "کامپاند"),
    ("bal", "Balancer", "بالانسر"),
    ("lrc", "Loopring", "لوپرینگ"),
    ("lpt", "Livepeer", "لایوپیر"),
    ("ens", "Ethereum Name Service", "اتریوم نیم سرویس"),
    ("sushi", "SushiSwap", "سوشی‌سواپ"),
    ("api3", "API3", "ای پی آی ۳"),
    ("one", "Harmony", "هارمونی"),
    ("glm", "Golem", "گولم"),
    ("dao", "DAO Maker", "دائو میکر"),
    ("cvc", "Civic", "سیویک"),
    ("nmr", "Numeraire", "نومریر"),
    ("storj", "Storj", "استورج"),
    ("snt", "Status", "استاتوس"),
    ("a", "Vaulta", "والتا"),
    ("zrx", "0x Protocol", "زیرو ایکس"),
    ("slp", "Smooth Love Potion", "اسموث لاو پوشن"),
    ("egld", "MultiversX", "مولتی ورس ایکس"),
    ("imx", "Immutable", "ایموتبل ایکس"),
    ("blur", "Blur", "بلر"),
    ("floki", "FLOKI", "فلوکی"),
    ("babydoge", "Baby Doge Coin", "بیبی دوج"),
    ("nft", "APENFT", "ایپ ان‌اف‌تی"),
    ("btt", "BitTorrent", "بی‌تی‌تی"),
    ("t", "Threshold", "ترشولد"),
    ("celr", "Celer Network", "سلر نتورک"),
    ("arb", "Arbitrum", "آربیتروم"),
    ("magic", "Treasure", "ترژر"),
    ("gmx", "GMX", "جی‌ام‌اکس"),
    ("band", "Band Protocol", "بند پروتکل"),
    ("cvx", "Convex Finance", "کانوکس فایننس"),
    ("ton", "Toncoin", "تون کوین"),
    ("mdt", "Measurable Data Token", "مژربل دیتا"),
    ("ssv", "ssv network", "اس‌اس‌وی نتورک"),
    ("omg", "OMG Network", "او‌ام‌جی نتورک"),
    ("wld", "Worldcoin", "ورلد کوین"),
    ("rdnt", "Radiant Capital", "رادیانت کپیتال"),
    ("jst", "JUST", "جاست"),
    ("render", "Render", "رندر"),
    ("bico", "Biconomy", "بیکونومی"),
    ("woo", "WOO Network", "وو نتورک"),
    ("skl", "SKALE", "اسکیل"),
    ("fet", "Fetch.ai", "فچ ای آی"),
    ("not", "Notcoin", "نات کوین"),
    ("trb", "Tellor", "تلور"),
    ("pepe", "Pepe", "پپه"),
    ("rsr", "Reserve Rights", "رزرو رایتس"),
    ("ethfi", "ether.fi", "اترفای"),
    ("agld", "Adventure Gold", "ادونچر گلد"),
    ("aevo", "Aevo", "آئوو"),
    ("om", "Mantra", "مانترا"),
    ("meme", "Memecoin", "میم کوین"),
    ("uma", "UMA", "اوما"),
    ("zro", "LayerZero", "لیر زیرو"),
    ("dogs", "Dogs", "داگز"),
    ("g", "Gravity", "گرویتی"),
    ("ondo", "Ondo", "اوندو"),
    ("auction", "Bounce Token", "بانس توکن"),
    ("ygg", "Yield Guild Games", "ییلد گیلد گیمز"),
    ("perp", "Perpetual Protocol", "پریپچوال پروتکل"),
    ("knc", "Kyber Network Crystal", "کایبر نتورک کریستال"),
    ("alpha", "Stella", "استلا"),
    ("bnt", "Bancor", "بنکور"),
    ("ren", "Ren", "رن"),
    ("badger", "Badger DAO", "بجر دائو"),
    ("id", "SPACE ID", "اسپیس آی‌دی"),
    ("cati", "Catizen", "کتیزن"),
    ("hmstr", "Hamster Kombat", "همستر کامبت"),
    ("eigen", "EigenCloud", "آیگن‌کلاود"),
    ("paxg", "Pax Gold", "پکس گلد"),
    ("xaut", "Tether Gold", "تتر گلد"),
    ("xtz", "Tezos", "تزوس"),
    ("ena", "Ethena", "اتنا"),
    ("pendle", "Pendle", "پندل"),
    ("x", "X Empire", "ایکس امپایر"),
    ("jasmy", "JasmyCoin", "جسمی کوین"),
    ("super", "SuperVerse", "سوپر ورس"),
    ("ankr", "Ankr", "انکر"),
    ("cake", "PancakeSwap", "پنکیک سواپ"),
    ("hot", "Holo", "هولو"),
    ("edu", "Open Campus", "اپن کمپس"),
    ("major", "Major", "میجر"),
    ("safe", "Safe", "سیف"),
    ("banana", "Banana Gun", "بنانا گان"),
    ("move", "Movement", "موومنت"),
    ("w", "Wormhole", "ورم هول"),
    ("strk", "Starknet", "استارک نت"),
    ("metis", "MetisDAO", "متیس دائو"),
    ("zil", "Zilliqa", "زیلیکا"),
    ("turbo", "Turbo", "توربو"),
    ("cookie", "Cookie DAO", "کوکی دائو"),
    ("cgpt", "ChainGPT", "چین جی پی تی"),
    ("s", "Sonic", "سونیک"),
    ("inj", "Injective", "اینجکتیو"),
    ("zec", "Zcash", "زی‌کش"),
    ("dexe", "Dexe", "دکسی"),
    ("ath", "Aethir", "ایثیر"),
    ("neiro", "Neiro", "نیرو"),
    ("bonk", "Bonk", "بونک"),
    ("morpho", "Morpho", "مورفو"),
    ("cat", "Simon's Cat", "کت"),
    ("form", "Four", "فور"),
    ("wif", "dogwifhat", "داگ ویف هت"),
    ("ray", "Raydium", "ریدیوم"),
    ("tnsr", "Tensor", "تنسور"),
    ("pha", "Phala Network", "فالا نتورک"),
    ("waxp", "WAX", "وکس"),
    ("fxs", "Frax", "فرکس"),
    ("twt", "Trust Wallet Token", "تراست ولت توکن"),
    ("orbs", "Orbs", "اربز"),
    ("sfp", "SafePal", "سیف پل"),
    ("zent", "Zentry", "زنتری"),
    ("ilv", "Illuvium", "ایلوویم"),
    ("rpl", "Rocket Pool", "راکت پول"),
    ("iq", "IQ", "آی کیو"),
    ("usual", "Usual", "یوژوال"),
    ("bigtime", "Big Time", "بیگ تایم"),
    ("vine", "Vine Coin", "واین کوین"),
    ("act", "Act I : The AI Prophecy", "اکت آی"),
    ("goat", "Goatseus Maximus", "گوتسئوس ماکسیموس"),
    ("anime", "Animecoin", "انیمه کوین"),
    ("stg", "Stargate Finance", "استارگیت فایننس"),
    ("cow", "CoW Protocol", "کاو پروتکل"),
    ("people", "ConstitutionDAO", "کانستیتوشن دائو"),
    ("powr", "Powerledger", "پاورلجر"),
    ("ach", "Alchemy Pay", "الکمی پی"),
    ("xai", "Xai", "ایکس ای آی"),
    ("aixbt", "aixbt by Virtuals", "ای آی ایکس بی تی"),
    ("virtual", "Virtuals Protocol", "ویرچوالز پروتکل"),
    ("kaito", "KAITO", "کایتو"),
    ("xlm", "Stellar", "استلار"),
    ("pengu", "Pudgy Penguins", "پاجی پنگوئن"),
    ("jup", "Jupiter", "ژوپیتر"),
    ("io", "io.net", "آیو"),
    ("pump", "Pump.fun", "پامپ فان"),
    ("layer", "Solayer", "سولیر"),
    ("pnut", "Peanut the Squirrel", "پینات"),
    ("bome", "BOOK OF MEME", "بوک آف میم"),
    ("syrup", "Maple Finance", "میپل فایننس"),
    ("alt", "Altlayer", "آلت‌لیر"),
    ("orca", "Orca", "اورکا"),
    ("zkj", "Polyhedra Network", "پلی‌هدرا نتورک"),
    ("jto", "Jito", "جیتو"),
    ("iotx", "IoTeX", "آیوتکس"),
    ("amp", "Amp", "امپ"),
    ("cfx", "Conflux", "کانفلاکس"),
    ("nexo", "Nexo", "نکسو"),
    ("sky", "Sky", "اسکای"),
    ("sahara", "Sahara AI", "ساهارا ای آی"),
    ("pyth", "Pyth Network", "پایث نتورک"),
    ("axl", "Axelar", "اکسلار"),
    ("sui", "Sui", "سویی"),
    ("bio", "Bio Protocol", "بیو پروتکل"),
    ("me", "Magic Eden", "مجیک ایدن"),
    ("sun", "Sun", "سان"),
    ("mew", "cat in a dogs world", "میو"),
    ("kmno", "Kamino Finance", "کامینو فایننس"),
    ("linea", "Linea", "لینیا"),
    ("aster", "Aster", "استر"),
    ("avnt", "Avantis", "آوانتیس"),
    ("bard", "Lombard", "لومبارد"),
    ("zkc", "Boundless", "باوندلس"),
    ("cheems", "Cheems", "چیمز"),
    ("op", "Optimism", "آپتیمیزم"),
    ("sei", "Sei", "سی"),
    ("usde", "USDe", "یو‌اس‌‌دی‌ای"),
    ("2z", "DoubleZero", "دابل‌زیرو"),
    ("aero", "Aerodrome Finance", "ایرودروم فایننس"),
    ("beamx", "Beam", "بیم"),
    ("toshi", "Toshi", "توشی"),
    ("moodeng", "Moo Deng", "مودنگ"),
    ("xvs", "Venus", "ونوس"),
    ("huma", "Huma Finance", "هوما فایننس"),
    ("spk", "Spark", "اسپارک"),
    ("sign", "Sign", "ساین"),
    ("pixel", "Pixels", "پیکسلز"),
    ("lqty", "Liquity", "لیکوییتی"),
    ("kernel", "KernelDAO", "کرنل‌دائو"),
    ("rlc", "iExec RLC", "آی اگزک آر‌ال‌سی"),
    ("degen", "Degen", "دیجن"),
    ("acx", "Across Protocol", "اکراس پروتکل"),
    ("ctc", "Creditcoin", "کردیت‌کوین"),
    ("giggle", "Giggle Fund", "گیگل فاند"),
    ("prove", "Succinct", "ساکسینکت"),
    ("met", "Meteora", "متئورا"),
    ("zora", "Zora", "زورا"),
    ("wal", "Walrus", "والروس"),
    ("prom", "Prom", "پرام"),
    ("zen", "Horizen", "هورایزن"),
    ("eul", "Euler", "اولر"),
    ("mmt", "Momentum", "مومنتوم"),
    ("kite", "Kite", "کایت"),
    ("wet", "Humidifi", "هیومیدیفای"),
    ("dood", "Doodles", "دودلز"),
    ("at", "Apro", "اپرو"),
    ("fluid", "Fluid", "فلوئید"),
    ("red", "RedStone", "رد استون"),
    ("la", "Lagrange", "لاگرانژ"),
    ("coti", "COTI", "کوتی"),
    ("hype", "Hyperliquid", "هایپرلیکویید"),
    ("lit", "Lighter", "لایتر"),
    ("zk", "ZkSync", "زی‌کی سینک"),
    ("dash", "Dash", "دش"),
    ("tao", "Bittensor", "بیت‌تنسور"),
    ("tia", "Celestia", "سلستیا"),
    ("brev", "Brevis", "برویس"),
    ("zama", "Zama", "زاما"),
    ("sent", "Sentient", "سنشنت"),
    ("slvon", "iShares Silver Trust Tokenized ETF", "نقره دیجیتال"),
    ("spx", "SPX6900", "اس پی ایکس"),
    ("chip", "USD AI", "یو‌اس‌دی ای آی"),
    ("awe", "AWE", "ای‌دبلیو‌ای"),
    ("based", "Based", "بیسد"),
    ("cfg", "Centrifuge", "سنتریفیوژ"),
    ("robo", "Fabric Protocol", "فبریک پروتکل"),
    ("home", "Defi App", "دیفای اپ"),
    ("myx", "MYX Finance", "میکس فایننس"),
    ("tel", "Telcoin", "تل‌کوین"),
    ("fartcoin", "Fartcoin", "فارت‌کوین"),
    ("brett", "Brett", "برت"),
    ("vsn", "Vision", "ویژن"),
    ("zbcn", "Zebec Network", "زبک نتورک"),
    ("gno", "Gnosis", "نوسیس"),
    ("hnt", "Helium", "هلیوم"),
    ("trac", "OriginTrail", "اوریجین‌تریل"),
    ("h", "Humanity Protocol", "هیومنیتی پروتکل"),
    ("mog", "Mog Coin", "ماگ‌کوین"),
    ("soon", "SOON", "سون"),
    ("beat", "Audiera", "آودیرا"),
    ("tibbir", "Ribbita by Virtuals", "ربیتا بای ویرچوالز"),
    ("ab", "AB", "ای بی"),
    ("pippin", "pippin", "پیپین"),
    ("b", "BUILDon", "بیلدآن"),
    ("drift", "Drift", "دریفت"),
    ("popcat", "Popcat", "پاپ‌کت"),
    ("alch", "Alchemist AI", "الکمیست ای‌آی"),
    ("power", "Power Protocol", "پاور پروتکل"),
    ("vvv", "Venice Token", "ونیس توکن"),
    ("audio", "Audius", "آدیوس"),
    ("river", "River", "ریور"),
    ("spell", "Spell Token", "اسپل توکن"),
    ("ub", "Unibase", "یونیبیس"),
    ("zig", "ZIGChain", "زیگ چین"),
    ("soso", "SoSoValue", "سوسو ولیو"),
    ("carv", "CARV", "کارو"),
    ("xyo", "XYO", "ایکس‌وای‌او"),
    ("useless", "Useless Coin", "یوزلس کوین"),
    ("npc", "Non-Playable Coin", "نان پلیبل کوین"),
    ("wmtx", "World Mobile Token", "ورلد موبایل توکن"),
    ("white", "WhiteRock", "وایت راک"),
    ("qai", "QuantixAI", "کوانتیکس ای‌آی"),
    ("geod", "GEODNET", "ژئودنت"),
    ("zbt", "ZEROBASE", "زیروبیس"),
    ("edge", "edgeX", "اج‌ایکس"),
    ("grass", "Grass", "گرس"),
    ("usoon", "United States Oil Tokenized Fund", "نفت دیجیتال"),
    ("tst", "Test", "تست"),
    ("dusk", "Dusk", "داسک"),
    ("open", "OpenLedger", "اوپن‌لجر"),
    ("copxon", "Global X Copper Miners Tokenized ETF", "مس دیجیتال"),
]


def upgrade() -> None:
    op.create_table(
        "tracked_coins",
        sa.Column("id",        sa.Integer(),      nullable=False),
        sa.Column("symbol",    sa.String(20),     nullable=False),
        sa.Column("name",      sa.String(255),    nullable=False, server_default=""),
        sa.Column("fa_name",   sa.String(255),    nullable=False, server_default=""),
        sa.Column("is_active", sa.Boolean(),      nullable=False, server_default=sa.text("TRUE")),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_index("ix_tracked_coins_symbol",    "tracked_coins", ["symbol"])
    op.create_index("ix_tracked_coins_is_active", "tracked_coins", ["is_active"])

    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO tracked_coins (symbol, name, fa_name, is_active) "
            "VALUES (:symbol, :name, :fa_name, TRUE) "
            "ON CONFLICT (symbol) DO NOTHING"
        ),
        [{"symbol": s, "name": n, "fa_name": fa} for s, n, fa in _COINS],
    )


def downgrade() -> None:
    op.drop_index("ix_tracked_coins_is_active", table_name="tracked_coins")
    op.drop_index("ix_tracked_coins_symbol",    table_name="tracked_coins")
    op.drop_table("tracked_coins")
