// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Signal Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the overall service health including PostgreSQL connection pool stats and Redis cache status.\nStatus is \"healthy\" when both DB and cache are reachable, \"degraded\" when cache is unreachable,\nand \"unhealthy\" when the database is unreachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy or degraded (cache issue)",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy (DB unreachable)",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/signals": {
            "get": {
                "description": "Returns a paginated list of trading signals. Scenarios and results are NOT included.\nResults are cached in Redis (TTL configurable, default 30s). Cache state is exposed via X-Cache header.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signals"
                ],
                "summary": "List signals",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by trading pair, case-insensitive (e.g. btcusdt or BTCUSDT)",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type (e.g. telegram, rss, http)",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source provider name",
                        "name": "source_provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated signal list",
                        "schema": {
                            "$ref": "#/definitions/signal_api_internal_repository.SignalsPage"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache state: HIT or MISS"
                            }
                        }
                    },
                    "408": {
                        "description": "DB query exceeded 5s timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Global rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Server at capacity – concurrency limit hit",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/signals/results": {
            "get": {
                "description": "Returns a paginated list of signals with full nested data: each Signal includes its Scenarios,\nand each Scenario includes its ScenarioResults. Uses 3 DB queries total (no N+1).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signals"
                ],
                "summary": "List signals with scenarios and results",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by trading pair",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source provider",
                        "name": "source_provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated signal list with nested scenarios and results",
                        "schema": {
                            "$ref": "#/definitions/signal_api_internal_repository.SignalsPage"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache state: HIT or MISS"
                            }
                        }
                    },
                    "408": {
                        "description": "DB query exceeded 5s timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Global rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Server at capacity",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/signals/source/{provider}": {
            "get": {
                "description": "Returns a paginated list of signals filtered by the source provider name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signals"
                ],
                "summary": "List signals by source provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source provider name (e.g. binance, coinbase, my_channel)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by trading pair",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated signal list",
                        "schema": {
                            "$ref": "#/definitions/signal_api_internal_repository.SignalsPage"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache state: HIT or MISS"
                            }
                        }
                    },
                    "408": {
                        "description": "DB query exceeded 5s timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Global rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Server at capacity",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/signals/source/{provider}/results": {
            "get": {
                "description": "Returns a paginated list of signals for a specific source provider, with full nested scenarios and results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signals"
                ],
                "summary": "List signals by provider with scenarios and results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source provider name",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by trading pair",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated signal list with nested scenarios and results",
                        "schema": {
                            "$ref": "#/definitions/signal_api_internal_repository.SignalsPage"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache state: HIT or MISS"
                            }
                        }
                    },
                    "408": {
                        "description": "DB query exceeded 5s timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Global rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Server at capacity",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/signals/{symbol}": {
            "get": {
                "description": "Returns a paginated list of signals filtered by the given trading pair symbol.\nSymbol matching is case-insensitive on input; stored values are uppercase (e.g. BTCUSDT).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signals"
                ],
                "summary": "List signals by symbol",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading pair symbol (e.g. BTCUSDT)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source provider",
                        "name": "source_provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated signal list",
                        "schema": {
                            "$ref": "#/definitions/signal_api_internal_repository.SignalsPage"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache state: HIT or MISS"
                            }
                        }
                    },
                    "408": {
                        "description": "DB query exceeded 5s timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Global rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Server at capacity",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/signals/{symbol}/results": {
            "get": {
                "description": "Returns a paginated list of signals for a specific trading pair, with full nested scenarios and results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "signals"
                ],
                "summary": "List signals by symbol with scenarios and results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trading pair symbol (e.g. BTCUSDT)",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source provider",
                        "name": "source_provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated signal list with nested scenarios and results",
                        "schema": {
                            "$ref": "#/definitions/signal_api_internal_repository.SignalsPage"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "Cache state: HIT or MISS"
                            }
                        }
                    },
                    "408": {
                        "description": "DB query exceeded 5s timeout",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Global rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Server at capacity",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler.CacheHealthStatus": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "unreachable"
                    ],
                    "example": "ok"
                }
            }
        },
        "internal_handler.DBHealthStatus": {
            "type": "object",
            "properties": {
                "acquired_conns": {
                    "type": "integer",
                    "example": 2
                },
                "idle_conns": {
                    "type": "integer",
                    "example": 8
                },
                "max_conns": {
                    "type": "integer",
                    "example": 50
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "unreachable"
                    ],
                    "example": "ok"
                },
                "total_conns": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "query timeout"
                },
                "retry_after": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_handler.HealthResponse": {
            "type": "object",
            "properties": {
                "cache": {
                    "$ref": "#/definitions/internal_handler.CacheHealthStatus"
                },
                "db": {
                    "$ref": "#/definitions/internal_handler.DBHealthStatus"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "healthy",
                        "degraded",
                        "unhealthy"
                    ],
                    "example": "healthy"
                }
            }
        },
        "signal_api_internal_repository.PageMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "signal_api_internal_repository.Scenario": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0,
                    "example": 0.85
                },
                "direction": {
                    "type": "string",
                    "enum": [
                        "long",
                        "short"
                    ],
                    "example": "long"
                },
                "entry_point": {
                    "type": "number",
                    "example": 49500
                },
                "entry_type": {
                    "type": "string",
                    "enum": [
                        "market",
                        "limit"
                    ],
                    "example": "limit"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "invalidation": {
                    "type": "string",
                    "example": "Daily close below 47000 invalidates setup"
                },
                "reasoning": {
                    "type": "string",
                    "example": "Strong support level with increasing volume and RSI divergence"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/signal_api_internal_repository.ScenarioResult"
                    }
                },
                "signal_id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "closed",
                        "invalidated"
                    ],
                    "example": "active"
                },
                "stop_loss": {
                    "type": "number",
                    "example": 47000
                },
                "take_profits": {
                    "type": "object"
                }
            }
        },
        "signal_api_internal_repository.ScenarioResult": {
            "type": "object",
            "properties": {
                "evaluated_at": {
                    "type": "string",
                    "example": "2024-01-16T14:30:00Z"
                },
                "hit_sl": {
                    "type": "number"
                },
                "hit_tp": {
                    "type": "number",
                    "example": 51000
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "max_drawdown": {
                    "type": "number",
                    "example": -2.3
                },
                "pnl_percent": {
                    "type": "number",
                    "example": 8.5
                },
                "result": {
                    "type": "string",
                    "enum": [
                        "win",
                        "loss",
                        "partial",
                        "pending"
                    ],
                    "example": "win"
                },
                "scenario_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "signal_api_internal_repository.Signal": {
            "type": "object",
            "properties": {
                "ai_summary": {
                    "type": "string",
                    "example": "Strong bullish breakout confirmed with high volume"
                },
                "analyzed_at": {
                    "type": "string",
                    "example": "2024-01-15T09:05:00Z"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T09:00:00Z"
                },
                "current_market_price": {
                    "type": "object"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "raw_text": {
                    "type": "string",
                    "example": "BTC breaks key resistance — targeting 52k"
                },
                "scenarios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/signal_api_internal_repository.Scenario"
                    }
                },
                "source": {
                    "type": "object"
                },
                "symbol": {
                    "type": "string",
                    "example": "BTCUSDT"
                },
                "trace_id": {
                    "type": "string",
                    "example": "3f2d1a9b-feed-4c2e-bae4-abc123def456"
                }
            }
        },
        "signal_api_internal_repository.SignalsPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/signal_api_internal_repository.Signal"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/signal_api_internal_repository.PageMeta"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Paginated trading signal endpoints with optional filtering by symbol, source type, and provider",
            "name": "signals"
        },
        {
            "description": "Service health and diagnostics",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Signal API",
	Description:      "Read-only REST API for accessing AI-analyzed trading signals, scenario plans, and result tracking.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
